# SPDX-FileCopyrightText: © 2022 Ryan C Schmidt <https://github.com/ryandesign>
#
# SPDX-License-Identifier: MIT

file(READ ${infile} data)
set(result 0)
while(NOT ${result} EQUAL -1)
    string(FIND "${data}" "<!--" result)
    if(NOT ${result} EQUAL -1)
        string(FIND "${data}" "-->" result)
        if(NOT ${result} EQUAL -1)
            string(REGEX REPLACE "-->(.*)" "<><>\\1" data "${data}")
            string(REGEX REPLACE "<!--.*<><>" "" data "${data}")
        endif()
    endif()
endwhile()
string(REGEX REPLACE "[ \t]*[\n\r]+[ \t]*" "\r" data "${data}")
string(REGEX REPLACE "^\r|\r$" "" data "${data}")
string(HEX "${data}" data)
string(REGEX MATCHALL "..?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?.?" data "${data}00")
file(WRITE "${outfile}" "#include \"ResourceConstants.h\"\n\n")
file(APPEND "${outfile}" "data '${rsrc_type}' (${rsrc_id}, purgeable) {\n")
foreach(chunk ${data})
    string(REGEX MATCHALL "..(..)?" chunk "${chunk}")
    list(JOIN chunk " " chunk)
    file(APPEND "${outfile}" "\t\$\"${chunk}\"\n")
endforeach()
file(APPEND "${outfile}" "};\n")
